Fix deploy branches config
apptension/aws-boilerplate pull request #71
Opened 2021-02-12 07:33 UTC by mkleszcz

Add lambda function to trigger and pass valid source reference to entrypoint.

2021-02-12 07:59 UTC, pziemkowski requested changes
I added some smaller comments.

2021-02-12 07:59 UTC, pziemkowski commented on infra/cdk/lib/stacks/env/ci/functions/trigger-entrypoint/index.js
> +            console.log(message);
console.log to be removed

2021-02-12 07:59 UTC, pziemkowski commented on infra/cdk/lib/stacks/env/ci/functions/trigger-entrypoint/index.js
> +        console.error(err);
Is this expected? Wouldn't we want this lambda to fail in this scenario?

2021-06-11 06:57 UTC, khanek approved these changes

2021-06-11 06:59 UTC, khanek commented
@pziemkowski Could you take a look at PR again?

2021-06-11 11:13 UTC, pziemkowski approved these changes

2021-06-11 11:48 UTC, merged